# Generated by Django 3.2.23 on 2023-11-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_p', models.IntegerField(primary_key=True, serialize=False)),
                ('notificaciones', models.CharField(max_length=255)),
                ('ofertas', models.CharField(max_length=255)),
                ('satisfaccion', models.IntegerField()),
                ('productosservicios', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('dispositivos', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
            ],
        ),
    ]
